# Generated by Django 4.2.5 on 2023-09-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaccess',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productaccess',
            old_name='user',
            new_name='user_id',
        ),
    ]
