# Generated by Django 4.2.5 on 2023-09-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_rename_product_productaccess_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LessonUser',
        ),
    ]
